2023-09-21 18:26:30,890:DEBUG:certbot._internal.main:certbot version: 2.6.0
2023-09-21 18:26:30,890:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-09-21 18:26:30,890:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/html', '--email', 'sammy@your_domain', '--agree-tos', '--no-eff-email', '--force-renewal', '-d', 'your_domain', '-d', 'www.your_domain']
2023-09-21 18:26:30,890:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-09-21 18:26:30,945:DEBUG:certbot._internal.log:Root logging level set at 30
2023-09-21 18:26:30,946:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-09-21 18:26:30,947:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0xffffa66872b0>
Prep: True
2023-09-21 18:26:30,947:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0xffffa66872b0> and installer None
2023-09-21 18:26:30,947:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-09-21 18:26:31,031:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-09-21 18:26:31,033:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-09-21 18:26:31,787:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2023-09-21 18:26:31,789:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 21 Sep 2023 18:26:31 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "br3fkWpg8C0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-09-21 18:26:31,790:DEBUG:acme.client:Requesting fresh nonce
2023-09-21 18:26:31,790:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-09-21 18:26:31,992:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-09-21 18:26:31,998:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 21 Sep 2023 18:26:31 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: OqS2LUF_PSB5v7HpJhMCp0ipssmw_dFZcYOSKtT50skpZ2Gffes
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-09-21 18:26:31,999:DEBUG:acme.client:Storing nonce: OqS2LUF_PSB5v7HpJhMCp0ipssmw_dFZcYOSKtT50skpZ2Gffes
2023-09-21 18:26:32,000:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:sammy@your_domain"\n  ],\n  "termsOfServiceAgreed": true\n}'
2023-09-21 18:26:32,008:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogInJ5SFl2ZWhMdDJJaUhQZmVQdURvcWltSFl2eGtPRk8tUGFqRU83cDZCdmR3aHlzQWpJX20xemg4UGFINmxwQm8zOHdVbE03QjQ0bEpiUnVGbjFtazdyaHNqeHAyc3YyRjd2emEyQXFtMC1IcXgxeFVsRWd6bEpQdUxyWHhwTWNjUDZ2X3NrRHd4SEE1M2owbVJNbDJCcTlnSnhvUHlyVWUzeW5CZGQwYWpsYzFLSFFub0ZzSURYbEdWTDRvU3dadmF2TDg5SFNlZ3dsRjlkYWtUSnZFeFBxVW1wLVZGY1IxY19LbkNLVEhqamZiMnFSUG9UUnhHckpEckFQMk9DX2lJWnBfdTQ0dkUxdHpZS0RNOE1oNnU2N1RIQkNXRjk0S0NjUFhibEpyQWI3blhCQ1dLOWxyUEV2NU5CMlBWTlM1OER1VUIyUzk2am43VkFRX2I4djhVdyIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiT3FTMkxVRl9QU0I1djdIcEpoTUNwMGlwc3Ntd19kRlpjWU9TS3RUNTBza3BaMkdmZmVzIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctYWNjdCJ9",
  "signature": "OS0-paQXzxQun3IVll780KBA5iVkcqTCr1oRQQmC8bqTmNI4cwJxDKHfBNm_QIG1GMfiz5MuL8HWJ_UUG_9awSAiNWt_N4GBmsqKQ1u6Rh4iPjvKxW3XugUwBDrDY5xPBlmUwF-nN8mEhYdW-9VM36QAbE0Fi7EyoSUtQv1fJjW2NbioVQLdBQ9CS9CdvMbBFaMP9nPuZXUhEbGFMrSzhdYWOuG-nIrMVD45r5nN962PLU9vIyVLbi2cPUhdZC1WLOiCmFUa9tjkCHuazWZjGNUJbQUClKt3DYh_zCxw4msI_aWi6XCUsApym2QPdNewPmH2wTr3KRERldUkwCAYgQ",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzpzYW1teUB5b3VyX2RvbWFpbiIKICBdLAogICJ0ZXJtc09mU2VydmljZUFncmVlZCI6IHRydWUKfQ"
}
2023-09-21 18:26:32,247:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 400 218
2023-09-21 18:26:32,251:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Date: Thu, 21 Sep 2023 18:26:32 GMT
Content-Type: application/problem+json
Content-Length: 218
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: a3DxhFlkSAqkDtOtfbPF16wBzNLDndAhrQOwqGPsOQxDhV-fJL8

{
  "type": "urn:ietf:params:acme:error:invalidContact",
  "detail": "Error creating new account :: contact email \"sammy@your_domain\" has invalid domain : Domain name contains an invalid character",
  "status": 400
}
2023-09-21 18:26:32,253:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 255, in perform_registration
    return acme.new_account(messages.NewRegistration.from_data(
  File "/opt/certbot/src/acme/acme/client.py", line 62, in new_account
    response = self._post(self.directory['newAccount'], new_account)
  File "/opt/certbot/src/acme/acme/client.py", line 366, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 739, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 752, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 603, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:invalidContact :: The provided contact URI was invalid :: Error creating new account :: contact email "sammy@your_domain" has invalid domain : Domain name contains an invalid character

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1579, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 830, in _init_le_client
    acc, acme = _determine_account(config)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 738, in _determine_account
    acc, acme = client.register(
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 209, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 264, in perform_registration
    config.email = display_ops.get_email(invalid=True)
  File "/opt/certbot/src/certbot/certbot/display/ops.py", line 54, in get_email
    code, email = display_util.input_text(invalid_prefix + msg if invalid else msg,
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 100, in input_text
    return obj.get_display().input(message, default=default, cli_flag=cli_flag,
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 152, in input
    ans = util.input_with_timeout(message)
  File "/opt/certbot/src/certbot/certbot/_internal/display/util.py", line 68, in input_with_timeout
    raise EOFError
EOFError
2023-09-21 18:26:32,259:ERROR:certbot._internal.log:An unexpected error occurred:
2023-09-21 18:26:32,263:ERROR:certbot._internal.log:EOFError
